artistAnt: ant_engine.c artist_ant.c advanceAnt.S getNextOrientation.S paint.S
	gcc -Wall -lm ant_engine.c artist_ant.c advanceAnt.S getNextOrientation.S paint.S -o artistAnt

clean:
	rm *.o artistAnt